# Generated by Django 6.0.5 on 2026-05-26 13:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelBatchTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_title', models.CharField(blank=True, max_length=255)),
                ('channel_url', models.URLField(max_length=1024)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1024)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_videos', models.IntegerField(default=0)),
                ('completed_videos', models.IntegerField(default=0)),
                ('zip_path', models.CharField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1024)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('format', models.CharField(choices=[('mp3', 'MP3'), ('mp4', 'MP4')], max_length=10)),
                ('quality', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting Metadata'), ('downloading', 'Downloading'), ('converting', 'Converting'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('speed', models.CharField(blank=True, max_length=50)),
                ('eta', models.CharField(blank=True, max_length=50)),
                ('file_size', models.CharField(blank=True, max_length=50)),
                ('file_path', models.CharField(blank=True, max_length=1024)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='downloader.channelbatchtask')),
            ],
        ),
    ]
