# Generated by Django 6.0.5 on 2026-05-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text='YouTube URL, video ID, or channel name to block (case-insensitive check)', max_length=512, unique=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for blocking (optional)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Y2Convert', max_length=100)),
                ('hero_title', models.CharField(default='YouTube to MP3 & MP4 Converter', max_length=255)),
                ('hero_subtitle', models.TextField(default='Fast, secure and unlimited YouTube video downloader. Save single videos or entire channels with a single click.')),
                ('footer_text', models.CharField(default='© 2026 Y2Convert. Built with Django and Python.', max_length=255)),
                ('footer_credits', models.CharField(default='By Karanjot Singh', max_length=255)),
                ('feature_1_title', models.CharField(default='High-Speed Downloads', max_length=100)),
                ('feature_1_desc', models.TextField(default='Features asynchronous parallel downloading on the server backend to process videos and full playlists at maximum speed.')),
                ('feature_2_title', models.CharField(default='Premium Quality', max_length=100)),
                ('feature_2_desc', models.TextField(default='Extracts files in crystal-clear MP3 audio quality (up to 320kbps) and original high-definition MP4 video quality.')),
                ('feature_3_title', models.CharField(default='Secure & Private', max_length=100)),
                ('feature_3_desc', models.TextField(default='100% safe from malware, redirects, and annoying ads. We process everything in the background for a secure experience.')),
                ('feature_4_title', models.CharField(default='Unlimited Converts', max_length=100)),
                ('feature_4_desc', models.TextField(default='No limitations on conversions or file sizes. Convert as many single videos or entire channels as you want, completely free.')),
            ],
            options={
                'verbose_name': 'Website Settings',
                'verbose_name_plural': 'Website Settings',
            },
        ),
    ]
